// ============================================================
// server.js — Main Express Server
// ============================================================
// This is the entry point for the backend.
// It sets up Express, connects middleware, and mounts routes.
// ============================================================

// Load environment variables from .env file (if it exists)
require("dotenv").config();

const express = require("express");
const cors    = require("cors");
const path    = require("path");

// Import our route files
const productRoutes = require("./routes/products");
const ideaRoutes = require("./routes/ideas");
const trendRoutes = require("./routes/trends");
const integrationsRoutes = require("./routes/integrations");
const etsyRoutes = require("./routes/etsy");

const app  = express();
const PORT = process.env.PORT || 3001;

const isLocalDevOrigin = (origin) => {
  if (!origin) return true;
  try {
    const u = new URL(origin);
    if (u.hostname === "localhost" || u.hostname === "127.0.0.1") return true;
  } catch {
    return false;
  }
  return false;
};

const parseClientOrigins = () => {
  const raw = process.env.CLIENT_ORIGIN;
  if (!raw || !String(raw).trim()) return [];
  return String(raw)
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
};

// ---- Middleware ----
app.use(
  cors({
    origin: (origin, callback) => {
      if (!origin || isLocalDevOrigin(origin)) {
        return callback(null, true);
      }
      const allowed = parseClientOrigins();
      if (allowed.length === 0) {
        return callback(null, true);
      }
      if (allowed.includes(origin)) {
        return callback(null, true);
      }
      return callback(null, false);
    }
  })
);
// Parse incoming JSON request bodies
app.use(express.json());

// ---- Static File Serving — Generated Digital Products ----
// Files generated by digitalProductService.js are saved to
// backend/generated-products/ and exposed at GET /downloads/*
// so the frontend can link directly to them for download.
//
// Example: GET /downloads/abc123-1700000000000-budget-planner.csv
//
// express.static streams the file and sets Content-Disposition
// headers automatically so browsers trigger a download.
const generatedProductsDir = path.join(__dirname, "generated-products");
app.use(
  "/downloads",
  express.static(generatedProductsDir, {
    // Tell browsers to download the file rather than open it inline
    setHeaders: (res, filePath) => {
      if (filePath.endsWith(".csv")) {
        res.setHeader("Content-Disposition", `attachment; filename="${path.basename(filePath)}"`);
        res.setHeader("Content-Type", "text/csv; charset=utf-8");
      }
    }
  })
);

// ---- Static File Serving — Uploaded / Generated Artwork ----
// Files saved by the upload-artwork route go to
// backend/generated-artwork/ and are served inline (not as
// downloads) at GET /artwork/* so the frontend can render
// <img> previews directly.
const generatedArtworkDir = path.join(__dirname, "generated-artwork");
app.use(
  "/artwork",
  express.static(generatedArtworkDir, {
    setHeaders: (res) => {
      // Allow cross-origin <img> embedding when the frontend is on a
      // different origin (e.g. Vercel → Render). Static files are
      // public read-only previews of user-owned uploads.
      res.setHeader("Cross-Origin-Resource-Policy", "cross-origin");
      res.setHeader("Cache-Control", "public, max-age=300");
    }
  })
);

// ---- Routes ----
// All product-related routes live under /api/products
app.use("/api/products", productRoutes);
// Ideas / research intake + opportunity scorer
app.use("/api/ideas", ideaRoutes);
// Trend Scanner — manual/assisted trend intake (converts to ideas)
app.use("/api/trends", trendRoutes);
// Integrations health endpoint — public, no secret values returned.
app.use("/api/integrations", integrationsRoutes);
// Etsy OAuth v3 (PKCE) — status, auth start, callback.
app.use("/api/etsy", etsyRoutes);

// ---- Health Check ----
// Useful to quickly verify the server is running
app.get("/api/health", (req, res) => {
  res.json({ status: "ok", message: "AI E-Commerce HQ backend is running!" });
});

// ---- Start Server ----
app.listen(PORT, "0.0.0.0", () => {
  console.log(`\n🚀 Backend server running at http://localhost:${PORT}`);
  console.log(`   Health check:    http://localhost:${PORT}/api/health`);
  console.log(`   Products API:    http://localhost:${PORT}/api/products`);
  console.log(`   Ideas API:       http://localhost:${PORT}/api/ideas`);
  console.log(`   Trends API:      http://localhost:${PORT}/api/trends`);
  console.log(`   Integrations:    http://localhost:${PORT}/api/integrations/status`);
  console.log(`   Etsy OAuth:      http://localhost:${PORT}/api/etsy/auth/start`);
  console.log(`   Downloads:       http://localhost:${PORT}/downloads/`);
  console.log(`   Artwork:         http://localhost:${PORT}/artwork/\n`);
});
